name: Run_Some_test

on:
  workflow_call:
    inputs:
      SOME:
        required: true
        type: string

jobs:
  run_something:
    runs-on: ubuntu-latest
    env:
      SOME: ${{ inputs.SOME }}
    steps:
      - name: echo a string
        run: |
          echo "Hello World here is some changes"
          echo ${{env.SOME}}