name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World here is some changes"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    with:
      environment: test
    steps:
      - name: Directory PowerShell
        run: Get-location
      - name: Directory Bash
        run: pwd
        shell: bash

#for testing manual triggering